apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fiuba-rpl-ingress-db
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: pgadmin
                port:
                  number: 80