apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource-v2-db
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: "learning.net.ar"
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: pgadmin
                port:
                  number: 80
  tls:
    - hosts:
        - "learning.net.ar"
      secretName: learning-certificate-tls-test