apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - image: dpage/pgadmin4
          imagePullPolicy: Always
          name: pgadmin
          readinessProbe:
            httpGet:
              path: /misc/ping
              port: 80
            initialDelaySeconds: 100
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 60
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /misc/ping
              port: 80
            initialDelaySeconds: 300
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 60
            periodSeconds: 60
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: rpl.fiuba@gmail.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: defaultpassword

---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  type: ClusterIP
  ports:
    - name: "pgadmin-http"
      port: 80
      targetPort: 80
    - name: "pgadmin-https"
      port: 443
      targetPort: 443
  selector:
    app: pgadmin

